#! /bin/sh

# Move to Taxicode App Directory
cd "$(dirname "$0")"

# Ask if taxicode / tpc / dashboard
while true; do
	read -p "Which app do you wish to compile? [ taxicode | tpc | dashboard | aa ] `echo $'\n> '`" app
	case $app in
		taxicode ) break;;
		tpc ) break;;
		dashboard ) break;;
		aa ) break;;
	esac
done

# Remove Taxicode.zip if exists
rm -f $app.zip

while true; do
	case $app in
		taxicode )

			# PREPARE TAXICODE APP
			mv www-taxicode www
			mv www/config-taxicode.xml www/config.xml
			mv www/boot-taxicode.js www/boot.js
			mv www/icon-taxicode.png www/icon.png
			zip -r $app.zip www plugins -x *res-tpc*
			mv www/icon.png www/icon-taxicode.png
			mv www/boot.js www/boot-taxicode.js
			mv www/config.xml www/config-taxicode.xml
			mv www www-taxicode

			break;;
		tpc )

			# PREPARE TAXI PRICE COMPARE APP
			mv www-taxicode www
			mv www/config-tpc.xml www/config.xml
			mv www/boot-tpc.js www/boot.js
			mv www/icon-tpc.png www/icon.png
			zip -r $app.zip www plugins -x *res-taxicode*
			mv www/icon.png www/icon-tpc.png
			mv www/boot.js www/boot-tpc.js
			mv www/config.xml www/config-tpc.xml
			mv www www-taxicode

			break;;
		aa )

			# PREPARE AA APP
			mv www-taxicode www
			mv www/config-aa.xml www/config.xml
			mv www/boot-aa.js www/boot.js
			mv www/icon-aa.png www/icon.png
			zip -r $app.zip www plugins -x *res-taxicode*
			mv www/icon.png www/icon-aa.png
			mv www/boot.js www/boot-aa.js
			mv www/config.xml www/config-aa.xml
			mv www www-taxicode

			break;;
		dashboard )

			# PREPARE DASHBOARD APP
			mv www-dashboard www
			zip -r $app.zip www plugins
			mv www www-dashboard
			
			break;;
	esac
done

# CLEAN / CREATE REPO
# repo="app-repos/taxicode-app-$app"
# test -d $repo || mkdir -p $repo
# find "$repo" -type f -not -name '.git*' | xargs rm -f
# unzip $app.zip "*" -d "$repo"

# GIT
# cd $repo

# git init
# git remote add origin "https://github.com/Web3r/taxicode-app-$app/.git"
# git add .
# git commit -m "Auto git commit - $(date)"
# git push origin master
# cd -

exit